import random

f = open("character.txt", "w")
f.write('Strength\n')
f.write(str(random.randint(1,20)))
f.write('\n')
f.write('Dexterity\n')
f.write(str(random.randint(1,20)))
f.write('\n')
f.write('Constitution\n')
f.write(str(random.randint(1,20)))
f.write('\n')
f.write('Intelligence\n')
f.write(str(random.randint(1,20)))
f.write('\n')
f.write('Wisdom\n')
f.write(str(random.randint(1,20)))
f.write('\n')
f.write('Charisma\n')
f.write(str(random.randint(1,20)))
f.close()

f = open("character.txt", "r")
print(f.read()) 
